// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: client/v1/tx_notification.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxCheckServiceCheckResponse_ResponseStatus int32

const (
	TxCheckServiceCheckResponse_STATUS_UNSPECIFIED TxCheckServiceCheckResponse_ResponseStatus = 0
	TxCheckServiceCheckResponse_COMMITTED          TxCheckServiceCheckResponse_ResponseStatus = 1
	TxCheckServiceCheckResponse_CANCELED           TxCheckServiceCheckResponse_ResponseStatus = 2
)

// Enum value maps for TxCheckServiceCheckResponse_ResponseStatus.
var (
	TxCheckServiceCheckResponse_ResponseStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "COMMITTED",
		2: "CANCELED",
	}
	TxCheckServiceCheckResponse_ResponseStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"COMMITTED":          1,
		"CANCELED":           2,
	}
)

func (x TxCheckServiceCheckResponse_ResponseStatus) Enum() *TxCheckServiceCheckResponse_ResponseStatus {
	p := new(TxCheckServiceCheckResponse_ResponseStatus)
	*p = x
	return p
}

func (x TxCheckServiceCheckResponse_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxCheckServiceCheckResponse_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v1_tx_notification_proto_enumTypes[0].Descriptor()
}

func (TxCheckServiceCheckResponse_ResponseStatus) Type() protoreflect.EnumType {
	return &file_client_v1_tx_notification_proto_enumTypes[0]
}

func (x TxCheckServiceCheckResponse_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxCheckServiceCheckResponse_ResponseStatus.Descriptor instead.
func (TxCheckServiceCheckResponse_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_client_v1_tx_notification_proto_rawDescGZIP(), []int{1, 0}
}

type TxCheckServiceCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxCheckServiceCheckRequest) Reset() {
	*x = TxCheckServiceCheckRequest{}
	mi := &file_client_v1_tx_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxCheckServiceCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCheckServiceCheckRequest) ProtoMessage() {}

func (x *TxCheckServiceCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_tx_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCheckServiceCheckRequest.ProtoReflect.Descriptor instead.
func (*TxCheckServiceCheckRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_tx_notification_proto_rawDescGZIP(), []int{0}
}

func (x *TxCheckServiceCheckRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TxCheckServiceCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxCheckServiceCheckResponse) Reset() {
	*x = TxCheckServiceCheckResponse{}
	mi := &file_client_v1_tx_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxCheckServiceCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCheckServiceCheckResponse) ProtoMessage() {}

func (x *TxCheckServiceCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_tx_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCheckServiceCheckResponse.ProtoReflect.Descriptor instead.
func (*TxCheckServiceCheckResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_tx_notification_proto_rawDescGZIP(), []int{1}
}

var File_client_v1_tx_notification_proto protoreflect.FileDescriptor

const file_client_v1_tx_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fclient/v1/tx_notification.proto\x12\tclient.v1\".\n" +
	"\x1aTxCheckServiceCheckRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"d\n" +
	"\x1bTxCheckServiceCheckResponse\"E\n" +
	"\x0eResponseStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\f\n" +
	"\bCANCELED\x10\x022h\n" +
	"\x0eTxCheckService\x12V\n" +
	"\x05Check\x12%.client.v1.TxCheckServiceCheckRequest\x1a&.client.v1.TxCheckServiceCheckResponseB\xa0\x01\n" +
	"\rcom.client.v1B\x13TxNotificationProtoP\x01Z5github.com/JrMarcco/jotify-api/api/client/v1;clientv1\xa2\x02\x03CXX\xaa\x02\tClient.V1\xca\x02\tClient\\V1\xe2\x02\x15Client\\V1\\GPBMetadata\xea\x02\n" +
	"Client::V1b\x06proto3"

var (
	file_client_v1_tx_notification_proto_rawDescOnce sync.Once
	file_client_v1_tx_notification_proto_rawDescData []byte
)

func file_client_v1_tx_notification_proto_rawDescGZIP() []byte {
	file_client_v1_tx_notification_proto_rawDescOnce.Do(func() {
		file_client_v1_tx_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_tx_notification_proto_rawDesc), len(file_client_v1_tx_notification_proto_rawDesc)))
	})
	return file_client_v1_tx_notification_proto_rawDescData
}

var file_client_v1_tx_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_v1_tx_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_v1_tx_notification_proto_goTypes = []any{
	(TxCheckServiceCheckResponse_ResponseStatus)(0), // 0: client.v1.TxCheckServiceCheckResponse.ResponseStatus
	(*TxCheckServiceCheckRequest)(nil),              // 1: client.v1.TxCheckServiceCheckRequest
	(*TxCheckServiceCheckResponse)(nil),             // 2: client.v1.TxCheckServiceCheckResponse
}
var file_client_v1_tx_notification_proto_depIdxs = []int32{
	1, // 0: client.v1.TxCheckService.Check:input_type -> client.v1.TxCheckServiceCheckRequest
	2, // 1: client.v1.TxCheckService.Check:output_type -> client.v1.TxCheckServiceCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_v1_tx_notification_proto_init() }
func file_client_v1_tx_notification_proto_init() {
	if File_client_v1_tx_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_tx_notification_proto_rawDesc), len(file_client_v1_tx_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_tx_notification_proto_goTypes,
		DependencyIndexes: file_client_v1_tx_notification_proto_depIdxs,
		EnumInfos:         file_client_v1_tx_notification_proto_enumTypes,
		MessageInfos:      file_client_v1_tx_notification_proto_msgTypes,
	}.Build()
	File_client_v1_tx_notification_proto = out.File
	file_client_v1_tx_notification_proto_goTypes = nil
	file_client_v1_tx_notification_proto_depIdxs = nil
}
