// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: client/v1/tx_notification.proto

package clientv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TxCheckService_Check_FullMethodName = "/client.v1.TxCheckService/Check"
)

// TxCheckServiceClient is the client API for TxCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TxCheckServiceClient interface {
	Check(ctx context.Context, in *TxCheckServiceCheckRequest, opts ...grpc.CallOption) (*TxCheckServiceCheckResponse, error)
}

type txCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTxCheckServiceClient(cc grpc.ClientConnInterface) TxCheckServiceClient {
	return &txCheckServiceClient{cc}
}

func (c *txCheckServiceClient) Check(ctx context.Context, in *TxCheckServiceCheckRequest, opts ...grpc.CallOption) (*TxCheckServiceCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxCheckServiceCheckResponse)
	err := c.cc.Invoke(ctx, TxCheckService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxCheckServiceServer is the server API for TxCheckService service.
// All implementations should embed UnimplementedTxCheckServiceServer
// for forward compatibility.
type TxCheckServiceServer interface {
	Check(context.Context, *TxCheckServiceCheckRequest) (*TxCheckServiceCheckResponse, error)
}

// UnimplementedTxCheckServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTxCheckServiceServer struct{}

func (UnimplementedTxCheckServiceServer) Check(context.Context, *TxCheckServiceCheckRequest) (*TxCheckServiceCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedTxCheckServiceServer) testEmbeddedByValue() {}

// UnsafeTxCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TxCheckServiceServer will
// result in compilation errors.
type UnsafeTxCheckServiceServer interface {
	mustEmbedUnimplementedTxCheckServiceServer()
}

func RegisterTxCheckServiceServer(s grpc.ServiceRegistrar, srv TxCheckServiceServer) {
	// If the following call pancis, it indicates UnimplementedTxCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TxCheckService_ServiceDesc, srv)
}

func _TxCheckService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxCheckServiceCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxCheckServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxCheckService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxCheckServiceServer).Check(ctx, req.(*TxCheckServiceCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TxCheckService_ServiceDesc is the grpc.ServiceDesc for TxCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TxCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.v1.TxCheckService",
	HandlerType: (*TxCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _TxCheckService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/v1/tx_notification.proto",
}
